---
- name: playbook to execute script
  hosts: "{{ HOSTS }}"
  gather_facts: yes
  
  tasks:
    - block:
        - name: Check if the file exists
          win_stat:
            path: "C:/Users/service_test.exe"
          register: File_output
          
        - name: Print result
          debug:
            msg: "File exists at the specified location: {{ File_output.stat.exists }}"
          
         
        - name: Execute Powershell Script present in the jump host
          win_command: powershell.exe -ExecutionPolicy ByPass -File "‪C:\Users\service_test.exe" -serviceName "{{ serviceName }}"
          register: result
          changed_when: false

        - name: Print the script Output
          debug:
            msg: "OUTPUT: SCRIPT RESULT : {{ result }}"
          
        - name: check the script.
          debug:
            msg: Script executed successfully
          when: result is succeeded
      rescue:
        - name: Print result
          debug:
            msg: "OUTPUT: FAILED : Script does not exist at the specified location {{ not File_output.stat.exists }}" 
          failed_when: true
          
        - name: Failed to Execute the script from jump host.
          debug:
            msg: "OUTPUT: FAILED : Failed to execute the script {{ result }}"
          failed_when: true
