---
- name: Fetch Server Config File from GitHub
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Read users from CSV file and return a dictionary
      community.general.read_csv:
        path: server_data.csv
      register: serverlist
      delegate_to: localhost

    - ansible.builtin.debug:
        msg: '{{ serverlist }}'

    - name: Assign values to variables
      set_fact:
        server_names: "{{ serverlist.list | map(attribute='ServerName') | list }}"
        vcenter_names: "{{ serverlist.list | map(attribute='vcenterName') | list }}"

    - debug:
        msg: "Server Name: {{ item.ServerName }}"
      with_items: "{{ serverlist.list }}"

    - name: Print Server List
      debug:
        msg: "ServerName: {{ server_names }}, vcenterName: {{ vcenter_names }}"
      
   



        
    
      

    # Optionally, you can add more tasks here to process or deploy the fetched config file
