---
- name: Fetch Server Config File from GitHub
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Ensure directory exists
      ansible.builtin.file:
        path: C:\Users\vv8\OneDrive - Capgemini\Desktop\Airbus_Snapshot_Usecase
        state: directory

    - name: Fetch server config file from GitHub
      ansible.builtin.git:
        repo: https://github.com/Vinod1410/Incident_repo.git
        dest: C:\Users\vv8\OneDrive - Capgemini\Desktop\Airbus_Snapshot_Usecase
        clone: yes
      register: server_details
      
    - name: Print stored value
      debug:
        var: server_details

    - name: Read server config file
      slurp:
        src: C:\Users\vv8\OneDrive - Capgemini\Desktop\Airbus_Snapshot_Usecase/server_config_file
      register: config_file_content

    - name: Assign server to variable
      set_fact:
        server_config: "{{ config_file_content.content | b64decode }}"
        
    - name: Print stored value
      debug:
        var: server_config
    
      

    # Optionally, you can add more tasks here to process or deploy the fetched config file
