---
- name: Read users from CSV file and return a dictionary
  hosts: localhost
  tasks:
    - name: Load data from CSV file
      set_fact:
        users_data: "{{ lookup('csvfile', 'server_data.csv') }}"
    - debug:
        var: users_data



        
    
      

    # Optionally, you can add more tasks here to process or deploy the fetched config file
