---
- name: Fetch Server Config File from GitHub
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Read users from CSV file and return a dictionary
      community.general.read_csv:
        path: server_data.csv
      register: serverlist
      delegate_to: localhost

    - ansible.builtin.debug:
        msg: '{{ serverlist }}'

    - name: Assign values to variables
      set_fact:
        server_names: "{{ serverlist | json_query('[].ServerName') }}"
        vcenter_names: "{{ serverlist | json_query('[].vcenterName') }}"

    - name: print the dict variables
      debug:
        msg: '{{ serverlist.list.ServerName }}'
   



        
    
      

    # Optionally, you can add more tasks here to process or deploy the fetched config file
