---
- name: Fetch Server Config File from GitHub
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Read users from CSV file and return a dictionary
      community.general.read_csv:
        path: server_data.csv
      register: serverlist
      delegate_to: localhost

    - ansible.builtin.debug:
        msg: '{{ serverlist }}'

    - name: Assign values to variables
      set_fact:
        server_names: "{{ server_names | default([]) + [item.ServerName] }}"
        vcenter_names: "{{ vcenter_names | default([]) + [item.vcenterName] }}"
      with_items: "{{ serverlist.list }}"

    - debug:
        msg: "Server Name: {{ server_names }}, Vcenter Name: {{ vcenter_names }}"
      

   
      
   



        
    
      

    # Optionally, you can add more tasks here to process or deploy the fetched config file
