---
- name: Fetch Server Config File from GitHub
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Fetch config file from GitHub
      uri:
        url: "https://github.com/Vinod1410/Incident_repo.git/server_config_file.xlsx"
        method: GET
      register: server_details

    - name: Display config file content
      debug:
        msg: "{{ server_details.content }}"

    - name: Assign server to variable
      set_fact:
        server_config: "{{ server_details.content | b64decode }}"

    - name: Print stored value
      debug:
        var: server_config
        
    
      

    # Optionally, you can add more tasks here to process or deploy the fetched config file
