---
- name: Fetch Server Config File from GitHub
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Ensure directory exists
      ansible.builtin.file:
        path: 'C:\Ansible_vinod'
        state: directory

    - name: Fetch server config file from GitHub
      ansible.builtin.git:
        repo: 'https://github.com/Vinod1410/Incident_repo.git'
        dest: 'C:\Ansible_vinod'
        clone: true
      register: server_details
      
    - name: Print stored value
      debug:
        var: server_details

    - name: Read server config file
      slurp:
        src: C:\Ansible_vinod/server_config_file
      register: config_file_content

    - name: Assign server to variable
      set_fact:
        server_config: "{{ config_file_content.content | b64decode }}"
        
    
      

    # Optionally, you can add more tasks here to process or deploy the fetched config file
