---
- name: Fetch Server Config File from GitHub
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Read users from CSV file and return a dictionary
      community.general.read_csv:
        path: server_data.csv
      register: serverlist
      delegate_to: localhost

    - ansible.builtin.debug:
        msg: '{{ serverlist }}'

    - debug:
        msg: "Server Name: {{ item.ServerName }}"
      with_items: "{{ serverlist.list }}"

   
      
   



        
    
      

    # Optionally, you can add more tasks here to process or deploy the fetched config file
