---
- name: Fetch Server Config File from GitHub
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Read users from CSV file and return a dictionary
      community.general.read_csv:
        path: server_data.csv
        key: Server Name
      register: serverlist
      delegate_to: localhost

    - ansible.builtin.debug:
        msg: 'serverdetails {{ serverlist.dict.Server Name }}'
   



        
    
      

    # Optionally, you can add more tasks here to process or deploy the fetched config file
