---
 - name: my first playbook
   hosts: "{{ HOSTS }}"
   tasks:
    - name: print message
      ansible.builtin.debug:
       msg: Hello everyone this is my first playbook on "{{ HOSTS }}"
       
    - name: Execute Powershell Script present in the jump host
      win_command: hostname 
      register: result
    - name: print hostname.
      debug:
        msg: "{{ result }}"
