---
- name: Launch Microsoft Teams and call a specific person
  hosts: localhost
  tasks:
    - name: Launch Microsoft Teams
      win_shell: |
        Start-Process "C:\Program Files (x86)\Microsoft\Teams\Update.exe" -ArgumentList "--processStart ""Teams.exe"" --process-start-args ""--callto:k.lavanya-meghana@capgemini.com""" -Wait
